### ISSUE TITLE
After new gbasf2 version (v5r7), BelleDIRAC/gbasf2/tools/setup.sh is not found at /cvmfs/belle.kek.jp/grid/gbasf2/pro/../../

### ISSUE THREAD

**Issue by sadlm8** [nils-braun/b2luigi#196] opened 2023-04-11 02:19 UTC
https://github.com/nils-braun/b2luigi/blob/438b28e9917de23b16e0ab9d379ad4941b93d8d1/b2luigi/batch/processes/gbasf2.py#L1099

There is no longer a gbasf2 folder at /cvmfs/belle.kek.jp/grid/gbasf2/pro/../../BelleDIRAC, which is where the batch.processes.get_gbasf2_env looks for the setup.sh file

I get this error when I try to run my b2luigi tasks:

`INFO: Worker Worker(salt=8596517225, workers=500, host=thread1.physics.adelaide.edu.au, username=sdelamot, pid=29092) was stopped. Shutting down Keep-Alive thread
Traceback (most recent call last):
  File "./udst_luigi_classes.py", line 217, in <module>
    main()
  File "./udst_luigi_classes.py", line 213, in main
    b2luigi.process(AggregatorTask(), workers=500, batch=True)
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/cli/process.py", line 111, in process
    runner.run_batched(task_list, cli_args, kwargs)
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/cli/runner.py", line 41, in run_batched
    run_luigi(task_list, cli_args, kwargs)
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/cli/runner.py", line 62, in run_luigi
    luigi.build(task_list, **kwargs)
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/luigi/interface.py", line 239, in build
    luigi_run_result = _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/luigi/interface.py", line 173, in _schedule_and_run
    success &= worker.run()
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/luigi/worker.py", line 1247, in run
    self._run_task(get_work_response.task_id)
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/luigi/worker.py", line 1041, in _run_task
    task_process = self._create_task_process(task)
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/batch/workers.py", line 40, in _create_task_process
    return process_class(task=task, scheduler=self._scheduler,
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/batch/processes/gbasf2.py", line 240, in __init__
    self.dirac_user = get_dirac_user()
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/batch/processes/gbasf2.py", line 947, in get_dirac_user
    setup_dirac_proxy()
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/batch/processes/gbasf2.py", line 960, in setup_dirac_proxy
    if get_proxy_info()["secondsLeft"] > 3600 * get_setting("gbasf2_min_proxy_lifetime", default=0):
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/batch/processes/gbasf2.py", line 934, in get_proxy_info
    proc = run_with_gbasf2(
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/batch/processes/gbasf2.py", line 872, in run_with_gbasf2
    gbasf2_env = get_gbasf2_env()
  File "/remote/adelphi/sdelamot/.local/lib/python3.8/site-packages/b2luigi/batch/processes/gbasf2.py", line 902, in get_gbasf2_env
    raise FileNotFoundError(
FileNotFoundError: Could not find gbasf2 setup file at:
/cvmfs/belle.kek.jp/grid/BelleDIRAC/gbasf2/tools/setup.sh.
Make sure that `gbasf2_install_directory` is set correctly. Current setting:
/cvmfs/belle.kek.jp/grid.`

(Apologies if not worded properly, I've not done much digging into gbasf2. I run a b2luigi code inherited from someone else!)

**Comment by meliache** [comment] 2023-04-11 14:11
This is a duplicate of issue #195, so I will close this and you can continue discussion over there. Thanks for reporting anyway, I'm aware many users are in need of a fix.

As you observed the setup-script path changed. I have pushed a fix (#162) to that to the `main` branch. It's not in any release yet but you can install that by cloning this repo and installing it or running 
``` bash
python3 -m pip install --upgrade "git+https://github.com/nils-braun/b2luigi"
```
(Hopefully that command works, I didn't test that command, but if it doesn't work you should figure out with some googling or chatgpt). However, from the discussion in #165 I guess that that there seem to be other issues due to changes in the latest gbasf2 version. Sadly I don't have time right now as I have to write up my PhD thesis and my certificates are getting deprecated. I hope somebody will provide a fix soon.

I suggest you subscribe to the issue #165 to reseive email notifications, and I also recommend pressing the `Watch` button for this repository, at least for new releases, as I try to be careful in release notes to report what changed.

**Closed by meliache** 2023-04-11 14:11 UTC
Labels: duplicate, wontfix, gbasf2
